# Generated by Django 4.0.4 on 2022-05-23 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_like'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'article')},
        ),
    ]
