# Generated by Django 4.0.4 on 2022-05-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_article_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletag',
            name='article',
            field=models.ManyToManyField(related_name='tags', to='web.article'),
        ),
    ]
